//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using HalconDotNet;
using ToolKits.FunctionModule;

namespace VisionMethonDll
{
    public class VisionMethon
    {
        #region 料片图谱
        /// <summary>
        /// 生成图谱
        /// </summary>
        /// <param name="ho_mapImage">生成的大图</param>
        /// <param name="hv_imageFolderPath">采样图的路径</param>
        /// <param name="hv_uvHxy">变换矩阵</param>
        /// <param name="hv_zoomFactor">缩放系数</param>
        /// <param name="hv_xSnapPosLT">大图0点为中心时轴坐标x</param>
        /// <param name="hv_ySnapPosLT">大图0点为中心时轴坐标y</param>
        /// <param name="hv_iFlag">字符串，为""无错</param>
        public static void gen_map_images(out HObject ho_mapImage, HTuple hv_imageFolderPath,
          HTuple hv_uvHxy, HTuple hv_zoomFactor, out HTuple hv_xSnapPosLT, out HTuple hv_ySnapPosLT,
          out HTuple hv_iFlag)
        {



            // Local iconic variables 

            HObject ho_Image, ho_firstImg;

            // Local control variables 

            HTuple hv_imagePaths = null, hv_rowCnt = null;
            HTuple hv_colCnt = null, hv_xSnapPos = null, hv_ySnapPos = null;
            HTuple hv_path = null, hv_xPosExist = null, hv_i = null;
            HTuple hv_j = new HTuple(), hv_imgPath = new HTuple();
            HTuple hv_imgExist = new HTuple(), hv_factor = null, hv_uvHxyScaled = null;
            HTuple hv_Width = null, hv_Height = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_mapImage);
            HOperatorSet.GenEmptyObj(out ho_Image);
            HOperatorSet.GenEmptyObj(out ho_firstImg);
            try
            {
                hv_iFlag = "";
                hv_xSnapPosLT = new HTuple();
                hv_ySnapPosLT = new HTuple();
                ho_mapImage.Dispose();
                HOperatorSet.GenEmptyObj(out ho_mapImage);

                hv_imagePaths = new HTuple();
                hv_rowCnt = 0;
                hv_colCnt = 0;
                hv_xSnapPos = new HTuple();
                hv_ySnapPos = new HTuple();

                hv_path = hv_imageFolderPath + "/Xpoint.dat";
                HOperatorSet.FileExists(hv_path, out hv_xPosExist);
                if ((int)(new HTuple(hv_xPosExist.TupleEqual(0))) != 0)
                {
                    hv_iFlag = "no x pose file exist!";
                    ho_Image.Dispose();
                    ho_firstImg.Dispose();

                    return;
                }
                HOperatorSet.ReadTuple(hv_path, out hv_xSnapPos);

                hv_path = hv_imageFolderPath + "/Ypoint.dat";
                HOperatorSet.FileExists(hv_path, out hv_xPosExist);
                if ((int)(new HTuple(hv_xPosExist.TupleEqual(0))) != 0)
                {
                    hv_iFlag = "no y pose file exist!";
                    ho_Image.Dispose();
                    ho_firstImg.Dispose();

                    return;
                }
                HOperatorSet.ReadTuple(hv_path, out hv_ySnapPos);

                hv_i = 0;
                while ((int)(1) != 0)
                {
                    hv_j = 0;
                    while ((int)(1) != 0)
                    {
                        hv_imgPath = ((((hv_imageFolderPath + "/") + hv_i) + "-") + hv_j) + ".tiff";
                        HOperatorSet.FileExists(hv_imgPath, out hv_imgExist);
                        if ((int)(new HTuple(hv_imgExist.TupleEqual(0))) != 0)
                        {
                            break;
                        }
                        hv_imagePaths = hv_imagePaths.TupleConcat(hv_imgPath);
                        hv_j = hv_j + 1;
                    }
                    if ((int)(new HTuple(hv_j.TupleEqual(0))) != 0)
                    {
                        break;
                    }
                    hv_colCnt = hv_j.Clone();
                    hv_i = hv_i + 1;
                }
                hv_rowCnt = hv_i.Clone();
                if ((int)((new HTuple(hv_i.TupleEqual(0))).TupleAnd(new HTuple(hv_j.TupleEqual(
                    0)))) != 0)
                {
                    hv_iFlag = "no images exist!";
                    ho_Image.Dispose();
                    ho_firstImg.Dispose();

                    return;
                }

                ho_Image.Dispose();
                HOperatorSet.ReadImage(out ho_Image, hv_imagePaths);

                //ind := 1
                //for p := 0 to rowCnt-1 by 1
                //for q := 0 to colCnt-1 by 1
                //select_obj (Image, selectImg, ind)
                //*         zoom_image_factor (selectImg, ImageZoomed, zoomFactor, zoomFactor, 'constant')
                //*         write_image (ImageZoomed, 'tiff', 0, 'ZoomImageDir/'+p+'-'+q+'.tiff')
                //ind := ind+1
                //endfor
                //endfor
                //write_tuple (xSnapPos, 'ZoomImageDir/Xpoint.dat')
                //write_tuple (ySnapPos, 'ZoomImageDir/Ypoint.dat')

                hv_factor = 1.0;
                HOperatorSet.HomMat2dScale(hv_uvHxy, 1 / hv_zoomFactor, 1 / hv_zoomFactor, 0, 0,
                    out hv_uvHxyScaled);
                ho_mapImage.Dispose();
                tile_map_images(ho_Image, out ho_mapImage, hv_xSnapPos, hv_ySnapPos, hv_uvHxyScaled,
                    hv_rowCnt, hv_colCnt, hv_factor, out hv_iFlag);


                //*******计算die实际xy点位
                ho_firstImg.Dispose();
                HOperatorSet.SelectObj(ho_Image, out ho_firstImg, 1);
                HOperatorSet.GetImageSize(ho_firstImg, out hv_Width, out hv_Height);
                hv_xSnapPosLT = ((hv_xSnapPos.TupleSelect(0)) + (((hv_uvHxyScaled.TupleSelect(
                    0)) * (hv_Height - 1)) / 2.0)) + (((hv_uvHxyScaled.TupleSelect(1)) * (hv_Width - 1)) / 2.0);
                hv_ySnapPosLT = ((hv_ySnapPos.TupleSelect(0)) + (((hv_uvHxyScaled.TupleSelect(
                    3)) * (hv_Height - 1)) / 2.0)) + (((hv_uvHxyScaled.TupleSelect(4)) * (hv_Width - 1)) / 2.0);

                ho_Image.Dispose();
                ho_firstImg.Dispose();

                return;
            }
            catch (HalconException HDevExpDefaultException)
            {
                ho_Image.Dispose();
                ho_firstImg.Dispose();

                throw HDevExpDefaultException;
            }
        }

        /// <summary>
        /// 生成图谱点位
        /// </summary>
        /// <param name="ho_image">大图</param>
        /// <param name="ho_showContour">显示区</param>
        /// <param name="hv_modelType">模板类型</param>
        /// <param name="hv_modelID">模板id</param>
        /// <param name="hv_defRow">参考点横坐标</param>
        /// <param name="hv_defCol">参考点纵坐标</param>
        /// <param name="hv_scoreThresh">匹配分数</param>
        /// <param name="hv_xSnapPosLT">大图0点为中心时轴坐标x</param>
        /// <param name="hv_ySnapPosLT">大图0点为中心时轴坐标y</param>
        /// <param name="hv_uvHxy">Uv2Xy矩阵</param>
        /// <param name="hv_zoomFactor">降采样比例</param>
        /// <param name="hv_mapRowCnt">图谱行数</param>
        /// <param name="hv_mapColCnt">图谱列数</param>
        /// <param name="hv_mapX">图谱点位，三字扫描序，X</param>
        /// <param name="hv_mapY">图谱点位，三字扫描序，Y</param>
        /// <param name="hv_mapRow">图谱点位，三字扫描序，芯片在整个料片横坐标，0始</param>
        /// <param name="hv_mapCol">图谱点位，三字扫描序，芯片在整个料片纵坐标，0始</param>
        /// <param name="hv_mapU"></param>
        /// <param name="hv_mapV"></param>
        /// <param name="hv_dieWidth">缩放后芯片最小包围矩像素宽度</param>
        /// <param name="hv_dieHeight">缩放后芯片最小包围矩像素高度</param>
        /// <param name="hv_iFlag">操作成功标记，字符串，""成功</param>
        public static void get_mapping_coords(HObject ho_image, HObject ho_showContour, HTuple hv_modelType,
          HTuple hv_modelID, HTuple hv_defRow, HTuple hv_defCol, HTuple hv_scoreThresh,
          HTuple hv_xSnapPosLT, HTuple hv_ySnapPosLT, HTuple hv_uvHxy, HTuple hv_zoomFactor,
          HTuple hv_mapRowCnt, HTuple hv_mapColCnt, out HTuple hv_mapX, out HTuple hv_mapY,
          out HTuple hv_mapRow, out HTuple hv_mapCol, out HTuple hv_mapU, out HTuple hv_mapV,
          out HTuple hv_dieWidth, out HTuple hv_dieHeight, out HTuple hv_iFlag)
        {




            // Local iconic variables 

            HObject ho_updateShowContour = null, ho_selectShowCont = null;
            HObject ho_selectRegion = null, ho_unionRegion = null, ho_sortedContours = null;
            HObject ho_affineShowCont = null, ho_affineSortedCont = null;
            HObject ho_firstCont = null;

            // Local control variables 

            HTuple hv_found_row = new HTuple(), hv_found_col = new HTuple();
            HTuple hv_found_angle = new HTuple(), hv_found_score = new HTuple();
            HTuple hv_update_def_row = new HTuple(), hv_update_def_col = new HTuple();
            HTuple hv_model_H_new = new HTuple(), hv_iFlag1 = new HTuple();
            HTuple hv_ind = new HTuple(), hv_unionRow = new HTuple();
            HTuple hv_unionCol = new HTuple(), hv_unionPhi = new HTuple();
            HTuple hv_unionLen1 = new HTuple(), hv_unionLen2 = new HTuple();
            HTuple hv_Row = new HTuple(), hv_Column = new HTuple();
            HTuple hv_Phi = new HTuple(), hv_Length1 = new HTuple();
            HTuple hv_Length2 = new HTuple(), hv_hom2d = new HTuple();
            HTuple hv_HomMat2DInvert = new HTuple(), hv_uvHxyScaled = new HTuple();
            HTuple hv_Row1 = new HTuple(), hv_Column1 = new HTuple();
            HTuple hv_Row2 = new HTuple(), hv_Column2 = new HTuple();
            HTuple hv__dieWidth = new HTuple(), hv__dieHeight = new HTuple();
            HTuple hv_colIndSeq = new HTuple(), hv_i = new HTuple();
            HTuple hv_rowIndSeq = new HTuple(), hv_xyHuv = new HTuple();
            HTuple hv_Exception = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_updateShowContour);
            HOperatorSet.GenEmptyObj(out ho_selectShowCont);
            HOperatorSet.GenEmptyObj(out ho_selectRegion);
            HOperatorSet.GenEmptyObj(out ho_unionRegion);
            HOperatorSet.GenEmptyObj(out ho_sortedContours);
            HOperatorSet.GenEmptyObj(out ho_affineShowCont);
            HOperatorSet.GenEmptyObj(out ho_affineSortedCont);
            HOperatorSet.GenEmptyObj(out ho_firstCont);
            hv_mapU = new HTuple();
            hv_mapV = new HTuple();
            try
            {
                hv_iFlag = "";
                hv_mapX = new HTuple();
                hv_mapY = new HTuple();
                hv_mapRow = new HTuple();
                hv_mapCol = new HTuple();
                hv_dieWidth = 0;
                hv_dieHeight = 0;

                try
                {

                    ho_updateShowContour.Dispose();
                    Vision.find_model(ho_image, ho_image, ho_showContour, out ho_updateShowContour,
                        hv_modelType, hv_modelID, -1, -1, hv_scoreThresh, 0, hv_defRow, hv_defCol,
                        out hv_found_row, out hv_found_col, out hv_found_angle, out hv_found_score,
                        out hv_update_def_row, out hv_update_def_col, out hv_model_H_new, out hv_iFlag1);
                    if ((int)(new HTuple(hv_iFlag1.TupleNotEqual(0))) != 0)
                    {
                        hv_iFlag = "match failed!";
                        ho_updateShowContour.Dispose();
                        ho_selectShowCont.Dispose();
                        ho_selectRegion.Dispose();
                        ho_unionRegion.Dispose();
                        ho_sortedContours.Dispose();
                        ho_affineShowCont.Dispose();
                        ho_affineSortedCont.Dispose();
                        ho_firstCont.Dispose();

                        return;
                    }
                    if ((int)(new HTuple((new HTuple(hv_found_score.TupleLength())).TupleLess(
                        hv_mapRowCnt * hv_mapColCnt))) != 0)
                    {
                        hv_iFlag = (new HTuple(new HTuple("match count ") + (new HTuple(hv_found_score.TupleLength()
                            ))) + " is not equal real die count ") + (hv_mapRowCnt * hv_mapColCnt);
                        ho_updateShowContour.Dispose();
                        ho_selectShowCont.Dispose();
                        ho_selectRegion.Dispose();
                        ho_unionRegion.Dispose();
                        ho_sortedContours.Dispose();
                        ho_affineShowCont.Dispose();
                        ho_affineSortedCont.Dispose();
                        ho_firstCont.Dispose();

                        return;
                    }
                    //******rotate
                    HOperatorSet.TupleGenSequence(1, hv_mapRowCnt * hv_mapColCnt, 1, out hv_ind);
                    ho_selectShowCont.Dispose();
                    HOperatorSet.SelectObj(ho_updateShowContour, out ho_selectShowCont, hv_ind);
                    ho_selectRegion.Dispose();
                    HOperatorSet.GenRegionContourXld(ho_selectShowCont, out ho_selectRegion,
                        "filled");
                    ho_unionRegion.Dispose();
                    HOperatorSet.Union1(ho_selectRegion, out ho_unionRegion);
                    HOperatorSet.SmallestRectangle2(ho_unionRegion, out hv_unionRow, out hv_unionCol,
                        out hv_unionPhi, out hv_unionLen1, out hv_unionLen2);
                    if ((int)(new HTuple(hv_unionPhi.TupleLess((new HTuple(-45)).TupleRad()))) != 0)
                    {
                        hv_unionPhi = hv_unionPhi + ((new HTuple(90)).TupleRad());
                    }
                    else if ((int)(new HTuple(hv_unionPhi.TupleGreater((new HTuple(45)).TupleRad()
                        ))) != 0)
                    {
                        hv_unionPhi = ((new HTuple(90)).TupleRad()) - hv_unionPhi;
                    }

                    //sort_contours_xld (selectShowCont, sortedContours, 'character', 'true', 'row')
                    //smallest_rectangle2_xld (sortedContours, Row, Column, Phi, Length1, Length2)
                    //tuple_sort_index (Column[0:mapColCnt-1], Indices)
                    //line_orientation (Row[Indices[0]], Column[Indices[0]], Row[Indices[|Indices|-1]], Column[Indices[|Indices|-1]], phi)
                    HOperatorSet.HomMat2dIdentity(out hv_hom2d);
                    HOperatorSet.HomMat2dRotate(hv_hom2d, -hv_unionPhi, 0, 0, out hv_hom2d);
                    ho_affineShowCont.Dispose();
                    HOperatorSet.AffineTransContourXld(ho_selectShowCont, out ho_affineShowCont,
                        hv_hom2d);
                    ho_sortedContours.Dispose();
                    HOperatorSet.SortContoursXld(ho_affineShowCont, out ho_sortedContours, "character",
                        "true", "row");
                    HOperatorSet.HomMat2dInvert(hv_hom2d, out hv_HomMat2DInvert);
                    ho_affineSortedCont.Dispose();
                    HOperatorSet.AffineTransContourXld(ho_sortedContours, out ho_affineSortedCont,
                        hv_HomMat2DInvert);
                    HOperatorSet.SmallestRectangle2Xld(ho_affineSortedCont, out hv_Row, out hv_Column,
                        out hv_Phi, out hv_Length1, out hv_Length2);
                    HOperatorSet.HomMat2dScale(hv_uvHxy, 1 / hv_zoomFactor, 1 / hv_zoomFactor, 0,
                        0, out hv_uvHxyScaled);
                    hv_mapX = (hv_xSnapPosLT + ((hv_uvHxyScaled.TupleSelect(0)) * (-hv_Row))) + ((hv_uvHxyScaled.TupleSelect(
                        1)) * (-hv_Column));
                    hv_mapY = (hv_ySnapPosLT + ((hv_uvHxyScaled.TupleSelect(3)) * (-hv_Row))) + ((hv_uvHxyScaled.TupleSelect(
                        4)) * (-hv_Column));

                    ho_firstCont.Dispose();
                    HOperatorSet.SelectObj(ho_showContour, out ho_firstCont, 1);
                    HOperatorSet.SmallestRectangle1Xld(ho_firstCont, out hv_Row1, out hv_Column1,
                        out hv_Row2, out hv_Column2);
                    hv__dieWidth = hv_Column2 - hv_Column1;
                    hv__dieHeight = hv_Row2 - hv_Row1;
                    hv_dieWidth = ((((hv_uvHxyScaled.TupleSelect(0)) * hv__dieHeight) + ((hv_uvHxyScaled.TupleSelect(
                        1)) * hv__dieWidth))).TupleAbs();
                    hv_dieHeight = ((((hv_uvHxyScaled.TupleSelect(3)) * hv__dieHeight) + ((hv_uvHxyScaled.TupleSelect(
                        4)) * hv__dieWidth))).TupleAbs();


                    HOperatorSet.TupleGenSequence(0, hv_mapColCnt - 1, 1, out hv_colIndSeq);
                    HTuple end_val55 = hv_mapRowCnt - 1;
                    HTuple step_val55 = 1;
                    for (hv_i = 0; hv_i.Continue(end_val55, step_val55); hv_i = hv_i.TupleAdd(step_val55))
                    {
                        HOperatorSet.TupleGenConst(hv_mapColCnt, hv_i, out hv_rowIndSeq);
                        hv_mapRow = hv_mapRow.TupleConcat(hv_rowIndSeq);
                        hv_mapCol = hv_mapCol.TupleConcat(hv_colIndSeq);
                    }

                    HOperatorSet.HomMat2dInvert(hv_uvHxyScaled, out hv_xyHuv);

                    hv_mapU = ((hv_xyHuv.TupleSelect(0)) * (hv_xSnapPosLT - hv_mapX)) + ((hv_xyHuv.TupleSelect(
                        1)) * (hv_ySnapPosLT - hv_mapY));
                    hv_mapV = ((hv_xyHuv.TupleSelect(3)) * (hv_xSnapPosLT - hv_mapX)) + ((hv_xyHuv.TupleSelect(
                        4)) * (hv_ySnapPosLT - hv_mapY));
                }
                // catch (Exception) 
                catch (HalconException HDevExpDefaultException1)
                {
                    HDevExpDefaultException1.ToHTuple(out hv_Exception);
                    GetErrInfo(hv_Exception, out hv_iFlag);
                }

                ho_updateShowContour.Dispose();
                ho_selectShowCont.Dispose();
                ho_selectRegion.Dispose();
                ho_unionRegion.Dispose();
                ho_sortedContours.Dispose();
                ho_affineShowCont.Dispose();
                ho_affineSortedCont.Dispose();
                ho_firstCont.Dispose();

                return;
            }
            catch (HalconException HDevExpDefaultException)
            {
                ho_updateShowContour.Dispose();
                ho_selectShowCont.Dispose();
                ho_selectRegion.Dispose();
                ho_unionRegion.Dispose();
                ho_sortedContours.Dispose();
                ho_affineShowCont.Dispose();
                ho_affineSortedCont.Dispose();
                ho_firstCont.Dispose();

                throw HDevExpDefaultException;
            }
        }
        /// <summary>
        /// 将区域转化为坐标
        /// </summary>
        /// <param name="ho_updateShowContour">芯片XLD</param>
        /// <param name="hv_xSnapPosLT">大图0点为中心时轴坐标x</param>
        /// <param name="hv_ySnapPosLT">大图0点为中心时轴坐标y</param>
        /// <param name="hv_uvHxy">Uv2Xy矩阵</param>
        /// <param name="hv_zoomFactor">降采样比例</param>
        /// <param name="hv_mapRowCnt">图谱行数</param>
        /// <param name="hv_mapColCnt">图谱列数</param>
        /// <param name="hv_mapX">图谱点位，三字扫描序，X</param>
        /// <param name="hv_mapY">图谱点位，三字扫描序，Y</param>
        /// <param name="hv_mapRow">图谱点位，三字扫描序，芯片在整个料片横坐标，0始</param>
        /// <param name="hv_mapCol">图谱点位，三字扫描序，芯片在整个料片纵坐标，0始</param>
        /// <param name="hv_mapU"></param>
        /// <param name="hv_mapV"></param>
        /// <param name="hv_dieWidth">缩放后芯片最小包围矩像素宽度</param>
        /// <param name="hv_dieHeight">缩放后芯片最小包围矩像素高度</param>
        /// <param name="hv_iFlag">操作成功标记，字符串，""成功</param>
        public static void get_mapping_coords_ext(HObject ho_updateShowContour, HTuple hv_xSnapPosLT,
      HTuple hv_ySnapPosLT, HTuple hv_uvHxy, HTuple hv_zoomFactor, HTuple hv_mapRowCnt,
      HTuple hv_mapColCnt, out HTuple hv_mapX, out HTuple hv_mapY, out HTuple hv_mapRow,
      out HTuple hv_mapCol, out HTuple hv_mapU, out HTuple hv_mapV, out HTuple hv_dieWidth,
      out HTuple hv_dieHeight, out HTuple hv_iFlag)
        {




            // Local iconic variables 

            HObject ho_selectShowCont = null, ho_selectRegion = null;
            HObject ho_unionRegion = null, ho_affineShowCont = null, ho_sortedContours = null;
            HObject ho_affineSortedCont = null, ho_firstCont = null;

            // Local control variables 

            HTuple hv_ind = new HTuple(), hv_unionRow = new HTuple();
            HTuple hv_unionCol = new HTuple(), hv_unionPhi = new HTuple();
            HTuple hv_unionLen1 = new HTuple(), hv_unionLen2 = new HTuple();
            HTuple hv_hom2d = new HTuple(), hv_Row3 = new HTuple();
            HTuple hv_Column3 = new HTuple(), hv_Phi1 = new HTuple();
            HTuple hv_Length11 = new HTuple(), hv_Length21 = new HTuple();
            HTuple hv_Indices = new HTuple(), hv_sortedIndices = new HTuple();
            HTuple hv_i = new HTuple(), hv_indices = new HTuple();
            HTuple hv_cols = new HTuple(), hv_Indices1 = new HTuple();
            HTuple hv_HomMat2DInvert = new HTuple(), hv_Row = new HTuple();
            HTuple hv_Column = new HTuple(), hv_Phi = new HTuple();
            HTuple hv_Length1 = new HTuple(), hv_Length2 = new HTuple();
            HTuple hv_uvHxyScaled = new HTuple(), hv_Row1 = new HTuple();
            HTuple hv_Column1 = new HTuple(), hv_Row2 = new HTuple();
            HTuple hv_Column2 = new HTuple(), hv__dieWidth = new HTuple();
            HTuple hv__dieHeight = new HTuple(), hv_colIndSeq = new HTuple();
            HTuple hv_rowIndSeq = new HTuple(), hv_xyHuv = new HTuple();
            HTuple hv_Exception = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_selectShowCont);
            HOperatorSet.GenEmptyObj(out ho_selectRegion);
            HOperatorSet.GenEmptyObj(out ho_unionRegion);
            HOperatorSet.GenEmptyObj(out ho_affineShowCont);
            HOperatorSet.GenEmptyObj(out ho_sortedContours);
            HOperatorSet.GenEmptyObj(out ho_affineSortedCont);
            HOperatorSet.GenEmptyObj(out ho_firstCont);
            hv_mapU = new HTuple();
            hv_mapV = new HTuple();
            try
            {
                hv_iFlag = "";
                hv_mapX = new HTuple();
                hv_mapY = new HTuple();
                hv_mapRow = new HTuple();
                hv_mapCol = new HTuple();
                hv_dieWidth = 0;
                hv_dieHeight = 0;

                try
                {
                    //******rotate
                    HOperatorSet.TupleGenSequence(1, hv_mapRowCnt * hv_mapColCnt, 1, out hv_ind);
                    ho_selectShowCont.Dispose();
                    HOperatorSet.SelectObj(ho_updateShowContour, out ho_selectShowCont, hv_ind);
                    ho_selectRegion.Dispose();
                    HOperatorSet.GenRegionContourXld(ho_selectShowCont, out ho_selectRegion,
                        "filled");
                    ho_unionRegion.Dispose();
                    HOperatorSet.Union1(ho_selectRegion, out ho_unionRegion);
                    HOperatorSet.SmallestRectangle2(ho_unionRegion, out hv_unionRow, out hv_unionCol,
                        out hv_unionPhi, out hv_unionLen1, out hv_unionLen2);
                    if ((int)(new HTuple(hv_unionPhi.TupleLess((new HTuple(-45)).TupleRad()))) != 0)
                    {
                        hv_unionPhi = hv_unionPhi + ((new HTuple(90)).TupleRad());
                    }
                    else if ((int)(new HTuple(hv_unionPhi.TupleGreater((new HTuple(45)).TupleRad()
                        ))) != 0)
                    {
                        hv_unionPhi = ((new HTuple(90)).TupleRad()) - hv_unionPhi;
                    }

                    HOperatorSet.HomMat2dIdentity(out hv_hom2d);
                    HOperatorSet.HomMat2dRotate(hv_hom2d, -hv_unionPhi, 0, 0, out hv_hom2d);
                    ho_affineShowCont.Dispose();
                    HOperatorSet.AffineTransContourXld(ho_selectShowCont, out ho_affineShowCont,
                        hv_hom2d);
                    HOperatorSet.SmallestRectangle2Xld(ho_affineShowCont, out hv_Row3, out hv_Column3,
                        out hv_Phi1, out hv_Length11, out hv_Length21);
                    HOperatorSet.TupleSortIndex(hv_Row3, out hv_Indices);
                    hv_sortedIndices = new HTuple();
                    HTuple end_val27 = hv_mapRowCnt - 1;
                    HTuple step_val27 = 1;
                    for (hv_i = 0; hv_i.Continue(end_val27, step_val27); hv_i = hv_i.TupleAdd(step_val27))
                    {
                        hv_indices = hv_Indices.TupleSelectRange(hv_i * hv_mapColCnt, ((hv_i + 1) * hv_mapColCnt) - 1);
                        hv_cols = hv_Column3.TupleSelect(hv_indices);
                        HOperatorSet.TupleSortIndex(hv_cols, out hv_Indices1);
                        hv_sortedIndices = hv_sortedIndices.TupleConcat(hv_indices.TupleSelect(
                            hv_Indices1));
                    }
                    ho_sortedContours.Dispose();
                    HOperatorSet.SelectObj(ho_selectShowCont, out ho_sortedContours, hv_sortedIndices + 1);
                    HOperatorSet.HomMat2dInvert(hv_hom2d, out hv_HomMat2DInvert);
                    ho_affineSortedCont.Dispose();
                    HOperatorSet.AffineTransContourXld(ho_sortedContours, out ho_affineSortedCont,
                        hv_HomMat2DInvert);
                    HOperatorSet.SmallestRectangle2Xld(ho_affineSortedCont, out hv_Row, out hv_Column,
                        out hv_Phi, out hv_Length1, out hv_Length2);
                    HOperatorSet.HomMat2dScale(hv_uvHxy, 1 / hv_zoomFactor, 1 / hv_zoomFactor, 0,
                        0, out hv_uvHxyScaled);
                    hv_mapX = (hv_xSnapPosLT + ((hv_uvHxyScaled.TupleSelect(0)) * (-hv_Row))) + ((hv_uvHxyScaled.TupleSelect(
                        1)) * (-hv_Column));
                    hv_mapY = (hv_ySnapPosLT + ((hv_uvHxyScaled.TupleSelect(3)) * (-hv_Row))) + ((hv_uvHxyScaled.TupleSelect(
                        4)) * (-hv_Column));

                    ho_firstCont.Dispose();
                    HOperatorSet.SelectObj(ho_affineShowCont, out ho_firstCont, 1);
                    HOperatorSet.SmallestRectangle1Xld(ho_firstCont, out hv_Row1, out hv_Column1,
                        out hv_Row2, out hv_Column2);
                    hv__dieWidth = hv_Column2 - hv_Column1;
                    hv__dieHeight = hv_Row2 - hv_Row1;
                    hv_dieWidth = ((((hv_uvHxyScaled.TupleSelect(0)) * hv__dieHeight) + ((hv_uvHxyScaled.TupleSelect(
                        1)) * hv__dieWidth))).TupleAbs();
                    hv_dieHeight = ((((hv_uvHxyScaled.TupleSelect(3)) * hv__dieHeight) + ((hv_uvHxyScaled.TupleSelect(
                        4)) * hv__dieWidth))).TupleAbs();

                    HOperatorSet.TupleGenSequence(0, hv_mapColCnt - 1, 1, out hv_colIndSeq);
                    HTuple end_val49 = hv_mapRowCnt - 1;
                    HTuple step_val49 = 1;
                    for (hv_i = 0; hv_i.Continue(end_val49, step_val49); hv_i = hv_i.TupleAdd(step_val49))
                    {
                        HOperatorSet.TupleGenConst(hv_mapColCnt, hv_i, out hv_rowIndSeq);
                        hv_mapRow = hv_mapRow.TupleConcat(hv_rowIndSeq);
                        hv_mapCol = hv_mapCol.TupleConcat(hv_colIndSeq);
                    }

                    HOperatorSet.HomMat2dInvert(hv_uvHxyScaled, out hv_xyHuv);

                    hv_mapU = ((hv_xyHuv.TupleSelect(0)) * (hv_xSnapPosLT - hv_mapX)) + ((hv_xyHuv.TupleSelect(
                        1)) * (hv_ySnapPosLT - hv_mapY));
                    hv_mapV = ((hv_xyHuv.TupleSelect(3)) * (hv_xSnapPosLT - hv_mapX)) + ((hv_xyHuv.TupleSelect(
                        4)) * (hv_ySnapPosLT - hv_mapY));
                }
                // catch (Exception) 
                catch (HalconException HDevExpDefaultException1)
                {
                    HDevExpDefaultException1.ToHTuple(out hv_Exception);
                    GetErrInfo(hv_Exception, out hv_iFlag);
                }

                ho_selectShowCont.Dispose();
                ho_selectRegion.Dispose();
                ho_unionRegion.Dispose();
                ho_affineShowCont.Dispose();
                ho_sortedContours.Dispose();
                ho_affineSortedCont.Dispose();
                ho_firstCont.Dispose();

                return;
            }
            catch (HalconException HDevExpDefaultException)
            {
                ho_selectShowCont.Dispose();
                ho_selectRegion.Dispose();
                ho_unionRegion.Dispose();
                ho_affineShowCont.Dispose();
                ho_sortedContours.Dispose();
                ho_affineSortedCont.Dispose();
                ho_firstCont.Dispose();

                throw HDevExpDefaultException;
            }
        }
        public static void tile_map_images(HObject ho_Images, out HObject ho_TiledImage, HTuple hv_xSnapPos,
          HTuple hv_ySnapPos, HTuple hv_uvHxy, HTuple hv_rowCnt, HTuple hv_colCnt, HTuple hv_zoomFactor,
          out HTuple hv_iFlag)
        {




            // Local iconic variables 

            HObject ho_firstImage = null, ho_ImageZoomed = null;

            // Local control variables 

            HTuple hv_width = null, hv_height = null, hv_Width = new HTuple();
            HTuple hv_Height = new HTuple(), hv__xSnapPos = new HTuple();
            HTuple hv__ySnapPos = new HTuple(), hv_uvHxyScaled = new HTuple();
            HTuple hv_xyHuv = new HTuple(), hv_offsetRows = new HTuple();
            HTuple hv_offsetCols = new HTuple(), hv_row1 = new HTuple();
            HTuple hv_col1 = new HTuple(), hv_row2 = new HTuple();
            HTuple hv_col2 = new HTuple(), hv_Exception = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_TiledImage);
            HOperatorSet.GenEmptyObj(out ho_firstImage);
            HOperatorSet.GenEmptyObj(out ho_ImageZoomed);
            try
            {
                hv_iFlag = "";
                hv_width = 0;
                hv_height = 0;
                ho_TiledImage.Dispose();
                HOperatorSet.GenEmptyObj(out ho_TiledImage);

                //factor := 1/2.0
                try
                {
                    ho_firstImage.Dispose();
                    HOperatorSet.SelectObj(ho_Images, out ho_firstImage, 1);
                    HOperatorSet.GetImageSize(ho_firstImage, out hv_Width, out hv_Height);
                    //_xSnapPos := xSnapPos + uvHxy[0]*(-(Height-1)/2.0)+uvHxy[1]*(-(Width-1)/2.0)
                    //_ySnapPos := ySnapPos + uvHxy[3]*(-(Height-1)/2.0)+uvHxy[4]*(-(Width-1)/2.0)
                    hv__xSnapPos = (hv_xSnapPos + (((hv_uvHxy.TupleSelect(0)) * (hv_Height - 1)) / 2.0)) + (((hv_uvHxy.TupleSelect(
                        1)) * (hv_Width - 1)) / 2.0);
                    hv__ySnapPos = (hv_ySnapPos + (((hv_uvHxy.TupleSelect(3)) * (hv_Height - 1)) / 2.0)) + (((hv_uvHxy.TupleSelect(
                        4)) * (hv_Width - 1)) / 2.0);
                    HOperatorSet.HomMat2dScale(hv_uvHxy, 1 / hv_zoomFactor, 1 / hv_zoomFactor, 0,
                        0, out hv_uvHxyScaled);
                    HOperatorSet.HomMat2dInvert(hv_uvHxyScaled, out hv_xyHuv);
                    //affine_trans_point_2d (xyHuv, _xSnapPos, _ySnapPos, affineRows, affineCols)
                    //*     offsetRows1 := affineRows[0]-affineRows
                    //*     offsetCols1 := affineCols[0]-affineCols

                    //HTuple affineRows, affineCols;
                    //HOperatorSet.AffineTransPoint2d(hv_xyHuv, hv__xSnapPos, hv__ySnapPos, out affineRows, out affineCols);
                    //hv_offsetRows = affineRows[0] - affineRows;
                    //hv_offsetCols = affineCols[0] - affineCols;
                    //double d = 1.0 / (hv_uvHxyScaled[0] * hv_uvHxyScaled[4] - hv_uvHxyScaled[1] * hv_uvHxyScaled[3]);
                    //double a0 = hv_uvHxyScaled[4] * d;
                    //double a1 = -1*hv_uvHxyScaled[1] * d;
                    hv_offsetRows = ((hv_xyHuv.TupleSelect(0)) * ((hv__xSnapPos.TupleSelect(0)) - hv__xSnapPos)) + ((hv_xyHuv.TupleSelect(
                        1)) * ((hv__ySnapPos.TupleSelect(0)) - hv__ySnapPos));
                    hv_offsetCols = ((hv_xyHuv.TupleSelect(3)) * ((hv__xSnapPos.TupleSelect(0)) - hv__xSnapPos)) + ((hv_xyHuv.TupleSelect(
                        4)) * ((hv__ySnapPos.TupleSelect(0)) - hv__ySnapPos));


                    hv_width = ((((hv_offsetCols.TupleMax()) - (hv_offsetCols.TupleMin()))).TupleInt()
                        ) + hv_Width;
                    hv_height = ((((hv_offsetRows.TupleMax()) - (hv_offsetRows.TupleMin()))).TupleInt()
                        ) + hv_Height;
                    HOperatorSet.TupleGenConst(new HTuple(hv_offsetRows.TupleLength()), -1, out hv_row1);
                    HOperatorSet.TupleGenConst(new HTuple(hv_offsetRows.TupleLength()), -1, out hv_col1);
                    HOperatorSet.TupleGenConst(new HTuple(hv_offsetRows.TupleLength()), -1, out hv_row2);
                    HOperatorSet.TupleGenConst(new HTuple(hv_offsetRows.TupleLength()), -1, out hv_col2);
                    ho_ImageZoomed.Dispose();
                    HOperatorSet.ZoomImageFactor(ho_Images, out ho_ImageZoomed, hv_zoomFactor,
                        hv_zoomFactor, "constant");
                    ho_TiledImage.Dispose();
                    HOperatorSet.TileImagesOffset(ho_ImageZoomed, out ho_TiledImage, hv_offsetRows,
                        hv_offsetCols, hv_row1, hv_col1, hv_row2, hv_col2, hv_width, hv_height);
                }
                // catch (Exception) 
                catch (HalconException HDevExpDefaultException1)
                {
                    HDevExpDefaultException1.ToHTuple(out hv_Exception);
                    GetErrInfo(hv_Exception, out hv_iFlag);
                }

                ho_firstImage.Dispose();
                ho_ImageZoomed.Dispose();

                return;
            }
            catch (HalconException HDevExpDefaultException)
            {
                ho_firstImage.Dispose();
                ho_ImageZoomed.Dispose();

                throw HDevExpDefaultException;
            }
        }

        public static void GetErrInfo(HTuple hv_Exception, out HTuple hv_ErrMessage)
        {



            // Local iconic variables 
            // Initialize local and output iconic variables 
            hv_ErrMessage = (((("method [" + (hv_Exception.TupleSelect(7))) + "] use [") + (hv_Exception.TupleSelect(
                5))) + "] err! ") + (hv_Exception.TupleSelect(2));

            return;
        }

        /// <summary>
        /// 获取扫描点位
        /// </summary>
        /// <param name="hv_imageWidth">原始图宽</param>
        /// <param name="hv_imageHeight">原始图高</param>
        /// <param name="hv_widthFactor">原始图宽使用比例</param>
        /// <param name="hv_heightFactor">原始图高使用比例</param>
        /// <param name="hv_zoomFactor">缩放比例，跟前用保持一致</param>
        /// <param name="hv_dieWidth">缩放后芯片最小包围矩像素宽度</param>
        /// <param name="hv_dieHeight">缩放后芯片最小包围矩像素高度</param>
        /// <param name="hv_mapX">图谱点位，三字扫描序，X</param>
        /// <param name="hv_mapY">图谱点位，三字扫描序，Y</param>
        /// <param name="hv_uvHxy">映射矩阵</param>
        /// <param name="hv_xSnapPosLT">大图0点为中心时轴坐标X</param>
        /// <param name="hv_ySnapPosLT">大图0点为中心时轴坐标Y</param>
        /// <param name="hv_mapRowCnt">图谱行数</param>
        /// <param name="hv_mapColCnt">图谱列数</param>
        /// <param name="hv_M">视野内芯片行数</param>
        /// <param name="hv_N">视野内芯片列数</param>
        /// <param name="hv_snapMapX">拍照点位X</param>
        /// <param name="hv_snapMapY">拍照点Y</param>
        /// <param name="hv_iFlag">错误，""无错</param>
        public static void get_scan_points(out HObject ho_scanRects, HTuple hv_imageWidth, HTuple hv_imageHeight,
      HTuple hv_widthFactor, HTuple hv_heightFactor, HTuple hv_zoomFactor, HTuple hv_dieWidth,
      HTuple hv_dieHeight, HTuple hv_mapX, HTuple hv_mapY, HTuple hv_uvHxy, HTuple hv_xSnapPosLT,
      HTuple hv_ySnapPosLT, HTuple hv_mapRowCnt, HTuple hv_mapColCnt, out HTuple hv_M,
      out HTuple hv_N, out HTuple hv_snapMapX, out HTuple hv_snapMapY, out HTuple hv_snapMapRow,
      out HTuple hv_snapMapCol, out HTuple hv_iFlag)
        {



            // Local iconic variables 

            // Local control variables 

            HTuple hv_viewWidth = new HTuple(), hv_viewHeight = new HTuple();
            HTuple hv_uvHxyScaled = new HTuple(), hv_xyHuv = new HTuple();
            HTuple hv__dieHeight = new HTuple(), hv__dieWidth = new HTuple();
            HTuple hv_mapU = new HTuple(), hv_mapV = new HTuple();
            HTuple hv_minH = new HTuple(), hv_minV = new HTuple();
            HTuple hv_i = new HTuple(), hv_j = new HTuple(), hv_rowConst0 = new HTuple();
            HTuple hv_colConst0 = new HTuple(), hv_distH = new HTuple();
            HTuple hv_rowConst1 = new HTuple(), hv_colConst1 = new HTuple();
            HTuple hv_rowSeq = new HTuple(), hv_distV = new HTuple();
            HTuple hv_sortDistH = new HTuple(), hv_sortDistV = new HTuple();
            HTuple hv__minH = new HTuple(), hv__minV = new HTuple();
            HTuple hv_deltaRow = new HTuple(), hv_deltaCol = new HTuple();
            HTuple hv_scanRows = new HTuple(), hv_scanCols = new HTuple();
            HTuple hv_scanRowCnt = new HTuple(), hv_scanColCnt = new HTuple();
            HTuple hv_I = new HTuple(), hv_J = new HTuple(), hv_initScanRow = new HTuple();
            HTuple hv_initScanCol = new HTuple(), hv_p = new HTuple();
            HTuple hv__snapMapX = new HTuple(), hv__snapMapY = new HTuple();
            HTuple hv_seqInd = new HTuple(), hv_rowIndConst = new HTuple();
            HTuple hv_colIndSeq = new HTuple(), hv__x = new HTuple();
            HTuple hv__y = new HTuple(), hv_Exception = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_scanRects);
            hv_iFlag = "";
            hv_M = 0;
            hv_N = 0;
            hv_snapMapX = new HTuple();
            hv_snapMapY = new HTuple();
            hv_snapMapRow = new HTuple();
            hv_snapMapCol = new HTuple();
            ho_scanRects.Dispose();
            HOperatorSet.GenEmptyObj(out ho_scanRects);

            try
            {
                hv_viewWidth = (hv_imageWidth * hv_widthFactor) * hv_zoomFactor;
                hv_viewHeight = (hv_imageHeight * hv_heightFactor) * hv_zoomFactor;
                //*****计算点扫拍照点位
                HOperatorSet.HomMat2dScale(hv_uvHxy, 1 / hv_zoomFactor, 1 / hv_zoomFactor, 0, 0,
                    out hv_uvHxyScaled);
                HOperatorSet.HomMat2dInvert(hv_uvHxyScaled, out hv_xyHuv);
                hv__dieHeight = ((((hv_xyHuv.TupleSelect(0)) * hv_dieWidth) + ((hv_xyHuv.TupleSelect(
                    1)) * (-hv_dieHeight)))).TupleAbs();
                hv__dieWidth = ((((hv_xyHuv.TupleSelect(3)) * hv_dieWidth) + ((hv_xyHuv.TupleSelect(
                    4)) * (-hv_dieHeight)))).TupleAbs();
                hv_mapU = ((hv_xyHuv.TupleSelect(0)) * (hv_xSnapPosLT - hv_mapX)) + ((hv_xyHuv.TupleSelect(
                    1)) * (hv_ySnapPosLT - hv_mapY));
                hv_mapV = ((hv_xyHuv.TupleSelect(3)) * (hv_xSnapPosLT - hv_mapX)) + ((hv_xyHuv.TupleSelect(
                    4)) * (hv_ySnapPosLT - hv_mapY));
                //gen_cross_contour_xld (Cross, mapUOut, mapVOut, 10, 0)
                //gen_rectangle1_contour_xld (rectangle, mapU-dieHeight/2.0, mapV-dieWidth/2.0, mapU+dieHeight/2.0, mapV+dieWidth/2.0)
                //***计算MN
                hv_M = 1;
                hv_N = 1;
                //***计算die之间最小间距minH,minV
                hv_minH = 99999;
                hv_minV = 99999;
                HTuple end_val27 = hv_mapRowCnt - 1;
                HTuple step_val27 = 1;
                for (hv_i = 0; hv_i.Continue(end_val27, step_val27); hv_i = hv_i.TupleAdd(step_val27))
                {
                    HTuple end_val28 = hv_mapColCnt - 1;
                    HTuple step_val28 = 1;
                    for (hv_j = 0; hv_j.Continue(end_val28, step_val28); hv_j = hv_j.TupleAdd(step_val28))
                    {
                        HOperatorSet.TupleGenConst(hv_mapColCnt, hv_mapU.TupleSelect((hv_i * hv_mapColCnt) + hv_j),
                            out hv_rowConst0);
                        HOperatorSet.TupleGenConst(hv_mapColCnt, hv_mapV.TupleSelect((hv_i * hv_mapColCnt) + hv_j),
                            out hv_colConst0);
                        HOperatorSet.DistancePp(hv_rowConst0, hv_colConst0, hv_mapU.TupleSelectRange(
                            hv_i * hv_mapColCnt, ((hv_i + 1) * hv_mapColCnt) - 1), hv_mapV.TupleSelectRange(
                            hv_i * hv_mapColCnt, ((hv_i + 1) * hv_mapColCnt) - 1), out hv_distH);

                        HOperatorSet.TupleGenConst(hv_mapRowCnt, hv_mapU.TupleSelect((hv_i * hv_mapColCnt) + hv_j),
                            out hv_rowConst1);
                        HOperatorSet.TupleGenConst(hv_mapRowCnt, hv_mapV.TupleSelect((hv_i * hv_mapColCnt) + hv_j),
                            out hv_colConst1);
                        HOperatorSet.TupleGenSequence(hv_j, ((hv_mapRowCnt * hv_mapColCnt) - 1) + hv_j,
                            hv_mapColCnt, out hv_rowSeq);
                        HOperatorSet.DistancePp(hv_rowConst1, hv_colConst1, hv_mapU.TupleSelect(
                            hv_rowSeq), hv_mapV.TupleSelect(hv_rowSeq), out hv_distV);

                        HOperatorSet.TupleSort(hv_distH, out hv_sortDistH);
                        HOperatorSet.TupleSort(hv_distV, out hv_sortDistV);
                        hv__minH = hv_sortDistH[1];
                        hv__minV = hv_sortDistV[1];
                        if ((int)(new HTuple(hv__minH.TupleLess(hv_minH))) != 0)
                        {
                            hv_minH = hv__minH.Clone();
                        }
                        if ((int)(new HTuple(hv__minV.TupleLess(hv_minV))) != 0)
                        {
                            hv_minV = hv__minV.Clone();
                        }
                    }
                }

                //****计算M
                while ((int)(1) != 0)
                {
                    if ((int)(new HTuple((((hv_viewHeight * hv_M) / (hv_M + 1))).TupleGreaterEqual(
                        hv__dieHeight + (hv_minV * (hv_M - 1))))) != 0)
                    {
                        hv_M = hv_M + 1;
                        continue;
                    }
                    else
                    {
                        break;
                    }
                }
                //*****计算N
                while ((int)(1) != 0)
                {
                    if ((int)(new HTuple((((hv_viewWidth * hv_N) / (hv_N + 1))).TupleGreaterEqual(hv__dieWidth + (hv_minH * (hv_N - 1))))) != 0)
                    {
                        hv_N = hv_N + 1;
                        continue;
                    }
                    else
                    {
                        break;
                    }
                }
                //stop ()
                //*******生成扫描点阵,先假设视野内左上角芯片距离视野中心关系为minH,minV;实际是需要根据uvHxy,Δu,Δv,计算图像中心所在的xy坐标

                hv_deltaRow = ((hv_M - 1) / 2.0) * hv_minV;
                hv_deltaCol = ((hv_N - 1) / 2.0) * hv_minH;
                hv_scanRows = new HTuple();
                hv_scanCols = new HTuple();
                hv_scanRowCnt = 0;
                hv_scanColCnt = 0;
                hv_i = 0;
                while ((int)(new HTuple(hv_i.TupleLess(hv_mapRowCnt))) != 0)
                {
                    hv_I = 1;
                    hv_j = 0;

                    while ((int)(new HTuple(hv_j.TupleLess(hv_mapColCnt))) != 0)
                    {
                        hv_J = 1;
                        hv_initScanRow = (hv_mapU.TupleSelect((hv_i * hv_mapColCnt) + hv_j)) + hv_deltaRow;
                        hv_initScanCol = (hv_mapV.TupleSelect((hv_i * hv_mapColCnt) + hv_j)) + hv_deltaCol;
                        //gen_cross_contour_xld (Cross2, initScanRow, initScanCol, 16, 0)
                        if ((int)(new HTuple(((hv_initScanCol + (hv_viewWidth / 2.0))).TupleGreaterEqual(
                            (hv_mapV.TupleSelect(((hv_i + 1) * hv_mapColCnt) - 1)) + (hv__dieWidth / 2.0)))) != 0)
                        {
                            //gen_cross_contour_xld (Cross2, initScanRow, initScanCol, 16, 0.25)
                            hv_scanRows = hv_scanRows.TupleConcat(hv_initScanRow);
                            hv_scanCols = hv_scanCols.TupleConcat(hv_initScanCol);
                            hv_scanColCnt = hv_scanColCnt + 1;
                            break;
                        }
                        else
                        {
                            HTuple end_val95 = hv_mapColCnt - 1;
                            HTuple step_val95 = 1;
                            for (hv_p = hv_j + 1; hv_p.Continue(end_val95, step_val95); hv_p = hv_p.TupleAdd(step_val95))
                            {
                                if ((int)(new HTuple(((hv_initScanCol + (hv_viewWidth / 2.0))).TupleGreaterEqual(
                                    (hv_mapV.TupleSelect((hv_i * hv_mapColCnt) + hv_p)) + (hv__dieWidth / 2.0)))) != 0)
                                {
                                    hv_J = hv_J + 1;
                                }
                                else
                                {
                                    //gen_cross_contour_xld (Cross2, initScanRow, initScanCol, 16, 0.25)
                                    hv_scanRows = hv_scanRows.TupleConcat(hv_initScanRow);
                                    hv_scanCols = hv_scanCols.TupleConcat(hv_initScanCol);
                                    hv_scanColCnt = hv_scanColCnt + 1;
                                    break;
                                }
                            }
                        }
                        hv_j = hv_j + hv_J;
                    }

                    if ((int)(new HTuple(((hv_initScanRow + (hv_viewHeight / 2.0))).TupleGreaterEqual(
                        (hv_mapU.TupleSelect((hv_mapRowCnt * hv_mapColCnt) - 1)) + (hv__dieHeight / 2.0)))) != 0)
                    {
                        hv_scanRowCnt = hv_scanRowCnt + 1;
                        break;
                    }
                    else
                    {
                        HTuple end_val114 = hv_mapRowCnt - 1;
                        HTuple step_val114 = 1;
                        for (hv_p = hv_i + 1; hv_p.Continue(end_val114, step_val114); hv_p = hv_p.TupleAdd(step_val114))
                        {
                            if ((int)(new HTuple(((hv_initScanRow + (hv_viewHeight / 2.0))).TupleGreaterEqual(
                                (hv_mapU.TupleSelect(((hv_p + 1) * hv_mapColCnt) - 1)) + (hv__dieHeight / 2.0)))) != 0)
                            {
                                hv_I = hv_I + 1;
                            }
                            else
                            {
                                hv_scanRowCnt = hv_scanRowCnt + 1;
                                break;
                            }
                        }
                    }
                    hv_i = hv_i + hv_I;
                }
                hv_scanColCnt = hv_scanColCnt / hv_scanRowCnt;

                ho_scanRects.Dispose();
                gen_rectangle1_contour_xld(out ho_scanRects, hv_scanRows - (hv_viewHeight / 2.0),
                    hv_scanCols - (hv_viewWidth / 2.0), hv_scanRows + (hv_viewHeight / 2.0), hv_scanCols + (hv_viewWidth / 2.0));
                //gen_cross_contour_xld (Cross3, scanRows, scanCols, 36, 0.5)

                hv__snapMapX = (hv_xSnapPosLT + ((hv_uvHxyScaled.TupleSelect(0)) * (-hv_scanRows))) + ((hv_uvHxyScaled.TupleSelect(
                    1)) * (-hv_scanCols));
                hv__snapMapY = (hv_ySnapPosLT + ((hv_uvHxyScaled.TupleSelect(3)) * (-hv_scanRows))) + ((hv_uvHxyScaled.TupleSelect(
                    4)) * (-hv_scanCols));
                //*****将扫描点位按弓字形排序
                HTuple end_val133 = hv_scanRowCnt - 1;
                HTuple step_val133 = 1;
                for (hv_i = 0; hv_i.Continue(end_val133, step_val133); hv_i = hv_i.TupleAdd(step_val133))
                {
                    HOperatorSet.TupleGenSequence(hv_i * hv_scanColCnt, ((hv_i + 1) * hv_scanColCnt) - 1,
                        1, out hv_seqInd);
                    HOperatorSet.TupleGenConst(hv_scanColCnt, hv_i, out hv_rowIndConst);
                    HOperatorSet.TupleGenSequence(0, hv_scanColCnt - 1, 1, out hv_colIndSeq);
                    if ((int)(new HTuple(((hv_i % 2)).TupleEqual(0))) != 0)
                    {
                        hv__x = hv__snapMapX.TupleSelect(hv_seqInd);
                        hv__y = hv__snapMapY.TupleSelect(hv_seqInd);
                    }
                    else
                    {
                        hv__x = ((hv__snapMapX.TupleSelect(hv_seqInd))).TupleInverse();
                        hv__y = ((hv__snapMapY.TupleSelect(hv_seqInd))).TupleInverse();
                        hv_colIndSeq = hv_colIndSeq.TupleInverse();
                    }
                    hv_snapMapX = hv_snapMapX.TupleConcat(hv__x);
                    hv_snapMapY = hv_snapMapY.TupleConcat(hv__y);
                    hv_snapMapRow = hv_snapMapRow.TupleConcat(hv_rowIndConst);
                    hv_snapMapCol = hv_snapMapCol.TupleConcat(hv_colIndSeq);
                }


            }
            // catch (Exception) 
            catch (HalconException HDevExpDefaultException1)
            {
                HDevExpDefaultException1.ToHTuple(out hv_Exception);
                GetErrInfo(hv_Exception, out hv_iFlag);
            }

            return;
        }


        /// <summary>
        /// 根据矫正点位更新芯片点位扫描点位
        /// </summary>
        /// <param name="ho_image">矫正点图片</param>
        /// <param name="ho_matchRegion">模板匹配区</param>
        /// <param name="hv_modelType">模板类型</param>
        /// <param name="hv_modelID">模板ID</param>
        /// <param name="hv_scoreThresh">匹配分数</param>
        /// <param name="hv_mapX">芯片X</param>
        /// <param name="hv_mapY">芯片Y</param>
        /// <param name="hv_snapMapX">扫描点X</param>
        /// <param name="hv_snapMapY">扫描点Y</param>
        /// <param name="hv_uvHxy">变换矩阵</param>
        /// <param name="hv_updateMapX">更新后芯片点X</param>
        /// <param name="hv_updateMapY">更新后芯片点Y</param>
        /// <param name="hv_updateSnapMapX">更新后扫描点X</param>
        /// <param name="hv_updateSnapMapY">更新后扫描点Y</param>
        /// <param name="hv_iFlag">标志</param>
        public static void update_map_points(HObject ho_image, HObject ho_matchRegion, HTuple hv_modelType,
          HTuple hv_modelID, HTuple hv_scoreThresh, HTuple hv_mapX, HTuple hv_mapY, HTuple hv_snapMapX,
          HTuple hv_snapMapY, HTuple hv_uvHxy, out HTuple hv_updateMapX, out HTuple hv_updateMapY,
          out HTuple hv_updateSnapMapX, out HTuple hv_updateSnapMapY, out HTuple hv_found_row, out HTuple hv_found_col, out HTuple hv_iFlag)
        {




            // Local iconic variables 

            HObject ho_showCount = null, ho_update_show_contour = null;

            // Local control variables 

            HTuple hv_found_angle = new HTuple(), hv_found_score = new HTuple();
            HTuple hv_update_def_row = new HTuple(), hv_update_def_col = new HTuple();
            HTuple hv_model_H_new = new HTuple(), hv_iFlag1 = new HTuple();
            HTuple hv_modelHimg = new HTuple(), hv_deltaX = new HTuple();
            HTuple hv_deltaY = new HTuple(), hv_modelHmap = new HTuple();
            HTuple hv_Exception = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_showCount);
            HOperatorSet.GenEmptyObj(out ho_update_show_contour);
            try
            {
                hv_iFlag = "";
                hv_updateMapX = new HTuple();
                hv_updateMapY = new HTuple();
                hv_updateSnapMapX = new HTuple();
                hv_updateSnapMapY = new HTuple();
                hv_found_row = new HTuple();
                hv_found_col = new HTuple();

                try
                {
                    ho_showCount.Dispose();
                    HOperatorSet.GenEmptyObj(out ho_showCount);
                    ho_update_show_contour.Dispose();
                    ToolKits.FunctionModule.Vision.find_model(ho_image, ho_matchRegion, ho_showCount, out ho_update_show_contour,
                        hv_modelType, hv_modelID, -1, -1, hv_scoreThresh, 1, -1, -1, out hv_found_row,
                        out hv_found_col, out hv_found_angle, out hv_found_score, out hv_update_def_row,
                        out hv_update_def_col, out hv_modelHimg, out hv_iFlag1);
                    if ((int)(new HTuple(hv_iFlag1.TupleNotEqual(0))) != 0)
                    {
                        hv_iFlag = "match failed!";
                        ho_showCount.Dispose();
                        ho_update_show_contour.Dispose();

                        return;
                    }
                    hv_deltaX = ((hv_uvHxy.TupleSelect(0)) * (-(hv_modelHimg.TupleSelect(2)))) + ((hv_uvHxy.TupleSelect(
                        1)) * (-(hv_modelHimg.TupleSelect(5))));
                    hv_deltaY = ((hv_uvHxy.TupleSelect(3)) * (-(hv_modelHimg.TupleSelect(2)))) + ((hv_uvHxy.TupleSelect(
                        4)) * (-(hv_modelHimg.TupleSelect(5))));
                    hv_modelHmap = hv_modelHimg.Clone();
                    if (hv_modelHmap == null)
                        hv_modelHmap = new HTuple();
                    hv_modelHmap[2] = hv_deltaX;
                    if (hv_modelHmap == null)
                        hv_modelHmap = new HTuple();
                    hv_modelHmap[5] = hv_deltaY;
                    //HTuple Sx, Sy, Phi, Theta, Tx, Ty;
                    //HOperatorSet.HomMat2dToAffinePar(hv_modelHmap, out Sx, out Sy, out Phi, out Theta, out Tx, out Ty);
                    HOperatorSet.AffineTransPoint2d(hv_modelHmap, hv_mapX, hv_mapY, out hv_updateMapX,
                        out hv_updateMapY);
                    HOperatorSet.AffineTransPoint2d(hv_modelHmap, hv_snapMapX, hv_snapMapY, out hv_updateSnapMapX,
                        out hv_updateSnapMapY);

                }
                // catch (Exception) 
                catch (HalconException HDevExpDefaultException1)
                {
                    HDevExpDefaultException1.ToHTuple(out hv_Exception);
                    GetErrInfo(hv_Exception, out hv_iFlag);
                }

                ho_showCount.Dispose();
                ho_update_show_contour.Dispose();

                return;
            }
            catch (HalconException HDevExpDefaultException)
            {
                ho_showCount.Dispose();
                ho_update_show_contour.Dispose();

                throw HDevExpDefaultException;
            }
        }

        /// <summary>
        /// 生成芯片匹配区
        /// </summary>
        /// <param name="ho_dieMatchRegion">芯片匹配区</param>
        /// <param name="hv_imgCenterX">图片中心X</param>
        /// <param name="hv_imgCenterY">图片中心Y</param>
        /// <param name="hv_dieWidth">芯片宽度</param>
        /// <param name="hv_dieHeight">芯片高度</param>
        /// <param name="hv_dieX">芯片X坐标</param>
        /// <param name="hv_dieY">芯片Y坐标</param>
        /// <param name="hv_uvHxy">UV2XY矩阵</param>
        /// <param name="hv_imgWidth">图片宽度</param>
        /// <param name="hv_imgHeight">图片高度</param>
        /// <param name="hv_imgWidthFactor">图片宽度有效比例</param>
        /// <param name="hv_imgHeightFactor">图片高度有效比例</param>
        /// <param name="hv_zoomFactor">缩放比例</param>
        /// <param name="hv_dilationSize">外扩尺寸,单位像素</param>
        /// <param name="hv_mapRowCnt">芯片总行数</param>
        /// <param name="hv_mapColCnt">芯片总列数</param>
        /// <param name="hv_dieRow">芯片当前行</param>
        /// <param name="hv_dieCol">芯片当前列</param>
        /// <param name="hv_iFlag">成功标志</param>
        public static void gen_die_match_region(out HObject ho_dieMatchRegion, HTuple hv_imgCenterX,
      HTuple hv_imgCenterY, HTuple hv_dieWidth, HTuple hv_dieHeight, HTuple hv_dieX,
      HTuple hv_dieY, HTuple hv_uvHxy, HTuple hv_imgWidth, HTuple hv_imgHeight, HTuple hv_imgWidthFactor,
      HTuple hv_imgHeightFactor, HTuple hv_zoomFactor, HTuple hv_dilationSize, HTuple hv_mapRowCnt,
      HTuple hv_mapColCnt, out HTuple hv_dieRow, out HTuple hv_dieCol, out HTuple hv_iFlag)
        {



            // Local iconic variables 

            // Local control variables 

            HTuple hv_uvHxyScaled = new HTuple(), hv_xyHuvScale = new HTuple();
            HTuple hv_viewWidth = new HTuple(), hv_viewHeight = new HTuple();
            HTuple hv_viewXLT = new HTuple(), hv_viewYLT = new HTuple();
            HTuple hv_viewXRB = new HTuple(), hv_viewYRB = new HTuple();
            HTuple hv_dieXLT = new HTuple(), hv_dieYLT = new HTuple();
            HTuple hv_dieXRB = new HTuple(), hv_dieYRB = new HTuple();
            HTuple hv_xLTGreater = new HTuple(), hv_yLTLess = new HTuple();
            HTuple hv_xRBLess = new HTuple(), hv_yRBGreater = new HTuple();
            HTuple hv_greater = new HTuple(), hv_greaterInd = new HTuple();
            HTuple hv_viewDieX = new HTuple(), hv_viewDieY = new HTuple();
            HTuple hv_deltaX = new HTuple(), hv_deltaY = new HTuple();
            HTuple hv_xyHuv = new HTuple(), hv_deltaRow = new HTuple();
            HTuple hv_deltaCol = new HTuple(), hv_dieImgRow = new HTuple();
            HTuple hv_dieImgCol = new HTuple(), hv_dieImgHeight = new HTuple();
            HTuple hv_dieImgWidth = new HTuple(), hv_row1 = new HTuple();
            HTuple hv_col1 = new HTuple(), hv_row2 = new HTuple();
            HTuple hv_col2 = new HTuple(), hv_Exception = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_dieMatchRegion);
            hv_iFlag = "";
            ho_dieMatchRegion.Dispose();
            HOperatorSet.GenEmptyObj(out ho_dieMatchRegion);
            hv_dieRow = new HTuple();
            hv_dieCol = new HTuple();
            try
            {
                HOperatorSet.HomMat2dScale(hv_uvHxy, 1 / hv_zoomFactor, 1 / hv_zoomFactor, 0, 0,
                    out hv_uvHxyScaled);
                HOperatorSet.HomMat2dInvert(hv_uvHxyScaled, out hv_xyHuvScale);
                hv_viewWidth = (((((hv_uvHxy.TupleSelect(0)) * hv_imgHeight) * hv_imgHeightFactor) + (((hv_uvHxy.TupleSelect(
                    1)) * hv_imgWidth) * hv_imgWidthFactor))).TupleAbs();
                hv_viewHeight = (((((hv_uvHxy.TupleSelect(3)) * hv_imgHeight) * hv_imgHeightFactor) + (((hv_uvHxy.TupleSelect(
                    4)) * hv_imgWidth) * hv_imgWidthFactor))).TupleAbs();
                hv_viewXLT = hv_imgCenterX - (hv_viewWidth / 2.0);
                hv_viewYLT = hv_imgCenterY + (hv_viewHeight / 2.0);
                hv_viewXRB = hv_imgCenterX + (hv_viewWidth / 2.0);
                hv_viewYRB = hv_imgCenterY - (hv_viewHeight / 2.0);
                hv_dieXLT = hv_dieX - (hv_dieWidth / 2.0);
                hv_dieYLT = hv_dieY + (hv_dieHeight / 2.0);
                hv_dieXRB = hv_dieX + (hv_dieWidth / 2.0);
                hv_dieYRB = hv_dieY - (hv_dieHeight / 2.0);

                //gen_rectangle1_contour_xld (rectangle, viewYLT, viewXLT, viewYRB, viewXRB)
                //gen_rectangle1_contour_xld (rectangle1, dieYLT, dieXLT, dieYRB, dieXRB)

                HOperatorSet.TupleGreaterEqualElem(hv_dieXLT, hv_viewXLT, out hv_xLTGreater);
                HOperatorSet.TupleGreaterEqualElem(hv_viewYLT, hv_dieYLT, out hv_yLTLess);
                HOperatorSet.TupleLessEqualElem(hv_dieXRB, hv_viewXRB, out hv_xRBLess);
                HOperatorSet.TupleLessEqualElem(hv_viewYRB, hv_dieYRB, out hv_yRBGreater);
                hv_greater = ((hv_xLTGreater * hv_yLTLess) * hv_xRBLess) * hv_yRBGreater;
                HOperatorSet.TupleFind(hv_greater, 1, out hv_greaterInd);
                if ((int)(new HTuple(hv_greaterInd.TupleEqual(-1))) != 0)
                {

                    return;
                }
                hv_viewDieX = hv_dieX.TupleSelect(hv_greaterInd);
                hv_viewDieY = hv_dieY.TupleSelect(hv_greaterInd);
                hv_deltaX = hv_imgCenterX - hv_viewDieX;
                hv_deltaY = hv_imgCenterY - hv_viewDieY;
                HOperatorSet.HomMat2dInvert(hv_uvHxy, out hv_xyHuv);
                hv_deltaRow = ((hv_xyHuv.TupleSelect(0)) * hv_deltaX) + ((hv_xyHuv.TupleSelect(
                    1)) * hv_deltaY);
                hv_deltaCol = ((hv_xyHuv.TupleSelect(3)) * hv_deltaX) + ((hv_xyHuv.TupleSelect(
                    4)) * hv_deltaY);
                hv_dieImgRow = ((hv_imgHeight - 1) / 2.0) + hv_deltaRow;
                hv_dieImgCol = ((hv_imgWidth - 1) / 2.0) + hv_deltaCol;
                hv_dieImgHeight = ((((hv_xyHuv.TupleSelect(0)) * hv_dieWidth) + ((hv_xyHuv.TupleSelect(
                    1)) * (-hv_dieHeight)))).TupleAbs();
                hv_dieImgWidth = ((((hv_xyHuv.TupleSelect(3)) * hv_dieWidth) + ((hv_xyHuv.TupleSelect(
                    4)) * (-hv_dieHeight)))).TupleAbs();
                hv_row1 = (hv_dieImgRow - (hv_dieImgHeight / 2.0)) - hv_dilationSize;
                hv_col1 = (hv_dieImgCol - (hv_dieImgWidth / 2.0)) - hv_dilationSize;
                hv_row2 = (hv_dieImgRow + (hv_dieImgHeight / 2.0)) + hv_dilationSize;
                hv_col2 = (hv_dieImgCol + (hv_dieImgWidth / 2.0)) + hv_dilationSize;
                if ((int)((new HTuple((new HTuple((new HTuple(hv_row1.TupleLess(0))).TupleOr(
                    new HTuple(hv_col1.TupleLess(0))))).TupleOr(
                    new HTuple(hv_row2.TupleGreater(hv_imgHeight))))).TupleOr(
                    new HTuple(hv_col2.TupleGreater(hv_imgWidth)))) != 0)
                {

                    return;
                }
                ho_dieMatchRegion.Dispose();
                HOperatorSet.GenRectangle1(out ho_dieMatchRegion, hv_row1, hv_col1, hv_row2,
                    hv_col2);
                hv_dieRow = hv_greaterInd / hv_mapColCnt;
                hv_dieCol = hv_greaterInd % hv_mapColCnt;
            }
            // catch (Exception) 
            catch (HalconException HDevExpDefaultException1)
            {
                HDevExpDefaultException1.ToHTuple(out hv_Exception);
                GetErrInfo(hv_Exception, out hv_iFlag);
            }



            return;
        }

        public static void find_model_ext(HObject ho_image, HObject ho_roi, HObject ho_show_contour,
            out HObject ho_update_show_contour, HTuple hv_model_type, HTuple hv_model_id,
            HTuple hv_angle_start, HTuple hv_angle_extent, HTuple hv_score_thresh, HTuple hv_match_num,
            HTuple hv_def_row, HTuple hv_def_col, out HTuple hv_found_row, out HTuple hv_found_col,
            out HTuple hv_found_angle, out HTuple hv_found_score, out HTuple hv_update_def_row,
            out HTuple hv_update_def_col, out HTuple hv_model_H_new, out HTuple hv_iFlag)
        {




            // Stack for temporary objects 
            HObject[] OTemp = new HObject[20];

            // Local iconic variables 

            HObject ho_complement_region, ho_paint_image;
            HObject ho_reduced_image, ho_affine_show_contour = null;

            // Local copy input parameter variables 
            HObject ho_image_COPY_INP_TMP;
            ho_image_COPY_INP_TMP = ho_image.CopyObj(1, -1);



            // Local control variables 

            HTuple hv_Channels = null, hv_inv_model_row = new HTuple();
            HTuple hv_inv_model_col = new HTuple(), hv_ncc_numlevs = new HTuple();
            HTuple hv_angle_step = new HTuple(), hv_ncc_metric = new HTuple();
            HTuple hv_local_row = new HTuple(), hv_local_col = new HTuple();
            HTuple hv_local_angle = new HTuple(), hv_local_score = new HTuple();
            HTuple hv_shape_numlevs = new HTuple(), hv_shape_scale_min = new HTuple();
            HTuple hv_shape_scale_max = new HTuple(), hv_shape_scale_step = new HTuple();
            HTuple hv_shape_metric = new HTuple(), hv_shape_min_contrast = new HTuple();
            HTuple hv_Greatereq = null, hv_GreaterInd = null, hv_model_row = new HTuple();
            HTuple hv_model_col = new HTuple(), hv_def_row_ind = new HTuple();
            HTuple hv_def_col_ind = new HTuple(), hv_i = new HTuple();
            HTuple hv_model_H_any = new HTuple(), hv__update_def_row = new HTuple();
            HTuple hv__update_def_col = new HTuple(), hv_update_model_row = new HTuple();
            HTuple hv_update_model_col = new HTuple();
            HTuple hv_angle_extent_COPY_INP_TMP = hv_angle_extent.Clone();
            HTuple hv_angle_start_COPY_INP_TMP = hv_angle_start.Clone();

            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_update_show_contour);
            HOperatorSet.GenEmptyObj(out ho_complement_region);
            HOperatorSet.GenEmptyObj(out ho_paint_image);
            HOperatorSet.GenEmptyObj(out ho_reduced_image);
            HOperatorSet.GenEmptyObj(out ho_affine_show_contour);
            try
            {
                hv_update_def_row = new HTuple();
                hv_update_def_col = new HTuple();
                hv_found_row = new HTuple();
                hv_found_col = new HTuple();
                hv_found_angle = new HTuple();
                hv_found_score = new HTuple();
                hv_model_H_new = new HTuple();
                hv_iFlag = 0;
                ho_update_show_contour.Dispose();
                HOperatorSet.GenEmptyObj(out ho_update_show_contour);

                ho_complement_region.Dispose();
                HOperatorSet.Complement(ho_roi, out ho_complement_region);
                HOperatorSet.CountChannels(ho_image_COPY_INP_TMP, out hv_Channels);
                if ((int)(new HTuple(hv_Channels.TupleNotEqual(1))) != 0)
                {
                    {
                        HObject ExpTmpOutVar_0;
                        HOperatorSet.Rgb1ToGray(ho_image_COPY_INP_TMP, out ExpTmpOutVar_0);
                        ho_image_COPY_INP_TMP.Dispose();
                        ho_image_COPY_INP_TMP = ExpTmpOutVar_0;
                    }
                }
                ho_paint_image.Dispose();
                HOperatorSet.PaintRegion(ho_complement_region, ho_image_COPY_INP_TMP, out ho_paint_image,
                    255, "fill");
                ho_reduced_image.Dispose();
                HOperatorSet.ReduceDomain(ho_paint_image, ho_roi, out ho_reduced_image);
                //******NCC/bin Ncc
                if ((int)(new HTuple(hv_model_type.TupleEqual(0))) != 0)
                {
                    HOperatorSet.GetNccModelOrigin(hv_model_id, out hv_inv_model_row, out hv_inv_model_col);
                    if ((int)((new HTuple(hv_angle_start_COPY_INP_TMP.TupleEqual(-1))).TupleOr(
                        new HTuple(hv_angle_extent_COPY_INP_TMP.TupleEqual(-1)))) != 0)
                    {
                        HOperatorSet.GetNccModelParams(hv_model_id, out hv_ncc_numlevs, out hv_angle_start_COPY_INP_TMP,
                            out hv_angle_extent_COPY_INP_TMP, out hv_angle_step, out hv_ncc_metric);
                    }
                    else
                    {
                        hv_angle_start_COPY_INP_TMP = hv_angle_start_COPY_INP_TMP.TupleRad();
                        hv_angle_extent_COPY_INP_TMP = hv_angle_extent_COPY_INP_TMP.TupleRad();
                    }
                    HOperatorSet.FindNccModel(ho_reduced_image, hv_model_id, hv_angle_start_COPY_INP_TMP,
                        hv_angle_extent_COPY_INP_TMP, 0.3, hv_match_num, 0.5, "true", 0, out hv_local_row,
                        out hv_local_col, out hv_local_angle, out hv_local_score);
                    //******Shape/Shape Xld
                }
                else
                {
                    HOperatorSet.GetShapeModelOrigin(hv_model_id, out hv_inv_model_row, out hv_inv_model_col);
                    if ((int)((new HTuple(hv_angle_start_COPY_INP_TMP.TupleEqual(-1))).TupleOr(
                        new HTuple(hv_angle_extent_COPY_INP_TMP.TupleEqual(-1)))) != 0)
                    {
                        HOperatorSet.GetShapeModelParams(hv_model_id, out hv_shape_numlevs, out hv_angle_start_COPY_INP_TMP,
                            out hv_angle_extent_COPY_INP_TMP, out hv_angle_step, out hv_shape_scale_min,
                            out hv_shape_scale_max, out hv_shape_scale_step, out hv_shape_metric,
                            out hv_shape_min_contrast);
                    }
                    else
                    {
                        hv_angle_start_COPY_INP_TMP = hv_angle_start_COPY_INP_TMP.TupleRad();
                        hv_angle_extent_COPY_INP_TMP = hv_angle_extent_COPY_INP_TMP.TupleRad();
                    }
                    HOperatorSet.FindShapeModel(ho_reduced_image, hv_model_id, hv_angle_start_COPY_INP_TMP,
                        hv_angle_extent_COPY_INP_TMP, 0.2, hv_match_num, 0.5, "least_squares",
                        0, 0.9, out hv_local_row, out hv_local_col, out hv_local_angle, out hv_local_score);
                }

                if ((int)(new HTuple((new HTuple(hv_local_score.TupleLength())).TupleLess(1))) != 0)
                {
                    hv_iFlag = -2;
                    ho_image_COPY_INP_TMP.Dispose();
                    ho_complement_region.Dispose();
                    ho_paint_image.Dispose();
                    ho_reduced_image.Dispose();
                    ho_affine_show_contour.Dispose();

                    return;
                }
                HOperatorSet.TupleGreaterEqualElem(hv_local_score, hv_score_thresh, out hv_Greatereq);
                HOperatorSet.TupleFind(hv_Greatereq, 1, out hv_GreaterInd);
                if ((int)(new HTuple(hv_GreaterInd.TupleEqual(-1))) != 0)
                {
                    hv_iFlag = -2;
                    ho_image_COPY_INP_TMP.Dispose();
                    ho_complement_region.Dispose();
                    ho_paint_image.Dispose();
                    ho_reduced_image.Dispose();
                    ho_affine_show_contour.Dispose();

                    return;
                }
                else
                {
                    //***获取模板中心坐标
                    hv_model_row = -hv_inv_model_row;
                    hv_model_col = -hv_inv_model_col;
                    HOperatorSet.TupleFind(hv_def_row, -1, out hv_def_row_ind);
                    HOperatorSet.TupleFind(hv_def_col, -1, out hv_def_col_ind);
                    for (hv_i = 0; (int)hv_i <= (int)((new HTuple(hv_GreaterInd.TupleLength())) - 1); hv_i = (int)hv_i + 1)
                    {
                        HOperatorSet.VectorAngleToRigid(0, 0, 0, hv_local_row.TupleSelect(hv_GreaterInd.TupleSelect(
                            hv_i)), hv_local_col.TupleSelect(hv_GreaterInd.TupleSelect(hv_i)),
                            hv_local_angle.TupleSelect(hv_GreaterInd.TupleSelect(hv_i)), out hv_model_H_any);
                        ho_affine_show_contour.Dispose();
                        HOperatorSet.AffineTransContourXld(ho_show_contour, out ho_affine_show_contour,
                            hv_model_H_any);

                        if ((int)((new HTuple(hv_def_row_ind.TupleEqual(-1))).TupleAnd(new HTuple(hv_def_col_ind.TupleEqual(
                            -1)))) != 0)
                        {
                            HOperatorSet.AffineTransPoint2d(hv_model_H_any, hv_def_row, hv_def_col,
                                out hv__update_def_row, out hv__update_def_col);
                        }
                        else
                        {
                            hv__update_def_row = new HTuple();
                            hv__update_def_col = new HTuple();
                        }
                        {
                            HObject ExpTmpOutVar_0;
                            HOperatorSet.ConcatObj(ho_update_show_contour, ho_affine_show_contour,
                                out ExpTmpOutVar_0);
                            ho_update_show_contour.Dispose();
                            ho_update_show_contour = ExpTmpOutVar_0;
                        }
                        //*****更新实际的模板坐标
                        HOperatorSet.AffineTransPoint2d(hv_model_H_any, hv_model_row, hv_model_col,
                            out hv_update_model_row, out hv_update_model_col);
                        hv_found_row = hv_found_row.TupleConcat(hv_update_model_row);
                        hv_found_col = hv_found_col.TupleConcat(hv_update_model_col);
                        hv_found_angle = hv_found_angle.TupleConcat(((hv_local_angle.TupleSelect(
                            hv_GreaterInd.TupleSelect(hv_i)))).TupleDeg());
                        hv_found_score = hv_found_score.TupleConcat(hv_local_score.TupleSelect(
                            hv_GreaterInd.TupleSelect(hv_i)));
                        hv_update_def_row = hv_update_def_row.TupleConcat(hv__update_def_row);
                        hv_update_def_col = hv_update_def_col.TupleConcat(hv__update_def_col);
                        hv_model_H_new = hv_model_H_new.TupleConcat(hv_model_H_any);
                    }
                }

                ho_image_COPY_INP_TMP.Dispose();
                ho_complement_region.Dispose();
                ho_paint_image.Dispose();
                ho_reduced_image.Dispose();
                ho_affine_show_contour.Dispose();

                return;
            }
            catch (HalconException HDevExpDefaultException)
            {
                ho_image_COPY_INP_TMP.Dispose();
                ho_complement_region.Dispose();
                ho_paint_image.Dispose();
                ho_reduced_image.Dispose();
                ho_affine_show_contour.Dispose();

                throw HDevExpDefaultException;
            }
        }

        public static void gen_rectangle1_contour_xld(out HObject ho_rectangle, HTuple hv_row1,
          HTuple hv_col1, HTuple hv_row2, HTuple hv_col2)
        {


            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_rectangle);
            ho_rectangle.Dispose();
            HOperatorSet.GenRectangle2ContourXld(out ho_rectangle, (hv_row1 + hv_row2) / 2.0,
                (hv_col1 + hv_col2) / 2.0, HTuple.TupleGenConst(new HTuple(hv_row1.TupleLength()
                ), 0), (hv_col2 - hv_col1) / 2.0, (hv_row2 - hv_row1) / 2.0);

            return;
        }
        #endregion
        #region 二维码
        /// <summary>
        ///1.训练二维码
        ///1.1 移动至二维码拍照位,采集图像
        ///1.2 交互画一个临时的包含二维码的区域ho_dataCode2DRegion
        ///1.3 调用函数TrainDataCode2D训练二维码
        /// </summary>
        /// <param name="ho_image"></param>
        /// <param name="ho_dataCode2DRegion"></param>
        /// <param name="ho_dataCode2DContour"></param>
        /// <param name="hv_dataCodeHandle"></param>
        /// <param name="hv_dataCodeType"></param>
        /// <param name="hv_dataCodeString"></param>
        /// <param name="hv_iFlag"></param>

        public static void TrainDataCode2D(HObject ho_image, HObject ho_dataCode2DRegion, out HObject ho_dataCode2DContour,
              out HTuple hv_dataCodeHandle, out HTuple hv_dataCodeType, out HTuple hv_dataCodeString,
              out HTuple hv_iFlag)
        {



            // Local iconic variables 

            HObject ho_reducedImg = null;

            // Local control variables 

            HTuple hv__dataCodeType = new HTuple(), hv_i = new HTuple();
            HTuple hv_resultHandles = new HTuple(), hv_Exception = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_dataCode2DContour);
            HOperatorSet.GenEmptyObj(out ho_reducedImg);
            try
            {
                hv_dataCodeHandle = new HTuple();
                hv_dataCodeType = new HTuple();
                hv_dataCodeString = new HTuple();
                ho_dataCode2DContour.Dispose();
                HOperatorSet.GenEmptyObj(out ho_dataCode2DContour);
                hv_iFlag = "";

                try
                {
                    ho_reducedImg.Dispose();
                    HOperatorSet.ReduceDomain(ho_image, ho_dataCode2DRegion, out ho_reducedImg
                        );
                    hv__dataCodeType = new HTuple();
                    hv__dataCodeType[0] = "Aztec Code";
                    hv__dataCodeType[1] = "Data Matrix ECC 200";
                    hv__dataCodeType[2] = "GS1 Aztec Code";
                    hv__dataCodeType[3] = "GS1 DataMatrix";
                    hv__dataCodeType[4] = "GS1 QR Code";
                    hv__dataCodeType[5] = "Micro QR Code";
                    hv__dataCodeType[6] = "PDF417";
                    hv__dataCodeType[7] = "QR Code";
                    for (hv_i = 0; (int)hv_i <= (int)((new HTuple(hv__dataCodeType.TupleLength())) - 1); hv_i = (int)hv_i + 1)
                    {
                        HOperatorSet.CreateDataCode2dModel(hv__dataCodeType.TupleSelect(hv_i),
                            new HTuple(), new HTuple(), out hv_dataCodeHandle);
                        ho_dataCode2DContour.Dispose();
                        HOperatorSet.FindDataCode2d(ho_reducedImg, out ho_dataCode2DContour, hv_dataCodeHandle,
                            "train", "all", out hv_resultHandles, out hv_dataCodeString);
                        if ((int)(new HTuple(hv_dataCodeString.TupleNotEqual(new HTuple()))) != 0)
                        {
                            hv_dataCodeType = hv__dataCodeType.TupleSelect(hv_i);
                            ho_reducedImg.Dispose();

                            return;
                        }
                    }
                }
                // catch (Exception) 
                catch (HalconException HDevExpDefaultException1)
                {
                    HDevExpDefaultException1.ToHTuple(out hv_Exception);
                    GetErrInfo(hv_Exception, out hv_iFlag);
                }

                ho_reducedImg.Dispose();

                return;
            }
            catch (HalconException HDevExpDefaultException)
            {
                ho_reducedImg.Dispose();

                throw HDevExpDefaultException;
            }
        }

        ////2.保存二维码模板,文件名以.dcm为扩展名
        //HOperatorSet.WriteDataCode2dModel(hv_dataCodeHandle, filePath);
        ////3.读取二维码模板
        //HOperatorSet.ReadDataCode2dModel(filePath, out hv_dataCodeHandle);	  
        ////4.清楚资源函数  
        //HOperatorSet.ClearDataCode2dModel(hv_dataCodeHandle);
        ////5.流程中读取二维码函数,二维码结果返回在hv_dataCodeString
        //HOperatorSet.FindDataCode2d(ho_Image1, out ho_dataCode2DContour, hv_dataCodeHandle, 
        //			  new HTuple(), new HTuple(), out hv_ResultHandles, out hv_dataCodeString);
        #endregion

    }

}