//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFAOIReview {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LFAOIReview.ExcelText", typeof(ExcelText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 操作员 的本地化字符串。
        /// </summary>
        internal static string AIOperator {
            get {
                return ResourceManager.GetString("AIOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 续 的本地化字符串。
        /// </summary>
        internal static string Continued {
            get {
                return ResourceManager.GetString("Continued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库 的本地化字符串。
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误类型 的本地化字符串。
        /// </summary>
        internal static string DefectType {
            get {
                return ResourceManager.GetString("DefectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每小时检测芯片数 的本地化字符串。
        /// </summary>
        internal static string DevicesPerHour {
            get {
                return ResourceManager.GetString("DevicesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次结束日期 的本地化字符串。
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次结束时间 的本地化字符串。
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合格 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 误检 的本地化字符串。
        /// </summary>
        internal static string FalseCall {
            get {
                return ResourceManager.GetString("FalseCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 误检率（%） 的本地化字符串。
        /// </summary>
        internal static string FalseCallDevicePercent {
            get {
                return ResourceManager.GetString("FalseCallDevicePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        internal static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 误检芯片数 的本地化字符串。
        /// </summary>
        internal static string NumberOfDevicesFalseCalled {
            get {
                return ResourceManager.GetString("NumberOfDevicesFalseCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次已检测芯片数 的本地化字符串。
        /// </summary>
        internal static string NumberOfDevicesInspected {
            get {
                return ResourceManager.GetString("NumberOfDevicesInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合格的芯片数 的本地化字符串。
        /// </summary>
        internal static string NumberOfDevicesPassed {
            get {
                return ResourceManager.GetString("NumberOfDevicesPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合格的芯片数 的本地化字符串。
        /// </summary>
        internal static string NumberOfDevicesRejected {
            get {
                return ResourceManager.GetString("NumberOfDevicesRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过的芯片数 的本地化字符串。
        /// </summary>
        internal static string NumberOfNoDies {
            get {
                return ResourceManager.GetString("NumberOfNoDies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次总芯片数 的本地化字符串。
        /// </summary>
        internal static string NumberOfStartQuantity {
            get {
                return ResourceManager.GetString("NumberOfStartQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已检测的盘数 的本地化字符串。
        /// </summary>
        internal static string NumberOfStripsInspected {
            get {
                return ResourceManager.GetString("NumberOfStripsInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检测的盘数 的本地化字符串。
        /// </summary>
        internal static string NumberOfStripsNotInspected {
            get {
                return ResourceManager.GetString("NumberOfStripsNotInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合格 的本地化字符串。
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编号 的本地化字符串。
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单盘芯片数 的本地化字符串。
        /// </summary>
        internal static string QuantityOfDevicesPerStrip {
            get {
                return ResourceManager.GetString("QuantityOfDevicesPerStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图谱 的本地化字符串。
        /// </summary>
        internal static string SheetName_MapOperator {
            get {
                return ResourceManager.GetString("SheetName_MapOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 综述 的本地化字符串。
        /// </summary>
        internal static string SheetName_SummaryOperator {
            get {
                return ResourceManager.GetString("SheetName_SummaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺陷类型 的本地化字符串。
        /// </summary>
        internal static string SheetName_UDD {
            get {
                return ResourceManager.GetString("SheetName_UDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过 的本地化字符串。
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次开始日期 的本地化字符串。
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次开始时间 的本地化字符串。
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘号 的本地化字符串。
        /// </summary>
        internal static string Strip {
            get {
                return ResourceManager.GetString("Strip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次总盘数 的本地化字符串。
        /// </summary>
        internal static string TotalNumberOfStrips {
            get {
                return ResourceManager.GetString("TotalNumberOfStrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合格率（%） 的本地化字符串。
        /// </summary>
        internal static string YieldByDevice {
            get {
                return ResourceManager.GetString("YieldByDevice", resourceCulture);
            }
        }
    }
}
